set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y18} [get_ports {rgmii_rxc}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W20} [get_ports {rgmii_txc}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA20} [get_ports {rgmii_txctl}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB21} [get_ports {rgmii_txd[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA21} [get_ports {rgmii_txd[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB22} [get_ports {rgmii_txd[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y21} [get_ports {rgmii_txd[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W22} [get_ports {rgmii_rst_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V18} [get_ports {rst_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K13} [get_ports {clk_test}]

set_property SLEW FAST [get_ports {rgmii_txd[*]}]
set_property SLEW FAST [get_ports rgmii_txc]
set_property SLEW FAST [get_ports rgmii_txctl]
create_clock -period 8.000 -name rx_clk [get_ports rgmii_rxc]
create_clock -period 8.000 -name tx_clk [get_ports rgmii_txc]
set_output_delay -clock [get_clocks {rgmii_txc}] -min -add_delay -2 [get_ports {rgmii_txd[*]}]
set_output_delay -clock [get_clocks {rgmii_txc}] -max -add_delay 2 [get_ports {rgmii_txd[*]}]
