create_clock -period 40.000 [get_ports i_clk_25m]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K4   } [get_ports {i_clk_25m}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U17  } [get_ports {i_rst_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N14  } [get_ports {o_led}]

# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_cke}] #恒3V3
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_cs_n}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[0]}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[1]}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[2]}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[3]}] #恒GND
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E14 } [get_ports {o_sdram_clk}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D17 } [get_ports {o_sdram_we_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D14 } [get_ports {o_sdram_cas_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A14 } [get_ports {o_sdram_ras_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D19 } [get_ports {o_sdram_ba[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B13 } [get_ports {o_sdram_ba[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C20 } [get_ports {o_sdram_addr[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C19 } [get_ports {o_sdram_addr[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C13 } [get_ports {o_sdram_addr[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F13 } [get_ports {o_sdram_addr[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G13 } [get_ports {o_sdram_addr[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G15 } [get_ports {o_sdram_addr[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F14 } [get_ports {o_sdram_addr[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F18 } [get_ports {o_sdram_addr[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E13 } [get_ports {o_sdram_addr[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E18 } [get_ports {o_sdram_addr[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C14 } [get_ports {o_sdram_addr[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F21 } [get_ports {io_sdram_dq[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E22 } [get_ports {io_sdram_dq[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F20 } [get_ports {io_sdram_dq[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E21 } [get_ports {io_sdram_dq[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F19 } [get_ports {io_sdram_dq[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D22 } [get_ports {io_sdram_dq[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E19 } [get_ports {io_sdram_dq[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D21 } [get_ports {io_sdram_dq[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  K21 } [get_ports {io_sdram_dq[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  L21 } [get_ports {io_sdram_dq[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  K22 } [get_ports {io_sdram_dq[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  M21 } [get_ports {io_sdram_dq[11]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  L20 } [get_ports {io_sdram_dq[12]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  M22 } [get_ports {io_sdram_dq[13]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  N20 } [get_ports {io_sdram_dq[14]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  M20 } [get_ports {io_sdram_dq[15]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B18 } [get_ports {io_sdram_dq[16]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D20 } [get_ports {io_sdram_dq[17]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A19 } [get_ports {io_sdram_dq[18]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A21 } [get_ports {io_sdram_dq[19]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A20 } [get_ports {io_sdram_dq[20]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B21 } [get_ports {io_sdram_dq[21]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C22 } [get_ports {io_sdram_dq[22]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B22 } [get_ports {io_sdram_dq[23]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G21 } [get_ports {io_sdram_dq[24]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G22 } [get_ports {io_sdram_dq[25]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  H20 } [get_ports {io_sdram_dq[26]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  H22 } [get_ports {io_sdram_dq[27]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  J20 } [get_ports {io_sdram_dq[28]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  J22 } [get_ports {io_sdram_dq[29]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G20 } [get_ports {io_sdram_dq[30]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  J21 } [get_ports {io_sdram_dq[31]}]

