set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design] 
set_property CONFIG_MODE SPIx1 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
 set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR NO [current_design]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_adv7611_pclk_IBUF]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K4} [get_ports {i_clk_25m}]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N14} [get_ports {o_led[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P15} [get_ports {o_led[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P16} [get_ports {o_led[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R16} [get_ports {o_led[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U17} [get_ports {i_key[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P17} [get_ports {i_key[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V17} [get_ports {i_key[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N17} [get_ports {i_key[3]}]


set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H19 } [get_ports {i_adv7611_data[22]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H18 } [get_ports {i_adv7611_data[23]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K16 } [get_ports {i_adv7611_data[20]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K19 } [get_ports {i_adv7611_data[21]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L19 } [get_ports {i_adv7611_data[18]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M18 } [get_ports {i_adv7611_data[19]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P20 } [get_ports {i_adv7611_data[16]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P19 } [get_ports {i_adv7611_data[17]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T20 } [get_ports {i_adv7611_data[14]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U20 } [get_ports {i_adv7611_data[15]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U21 } [get_ports {i_adv7611_data[12]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V22 } [get_ports {i_adv7611_data[13]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V20 } [get_ports {i_adv7611_data[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W22 } [get_ports {i_adv7611_data[11]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W21 } [get_ports {i_adv7611_data[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y22 } [get_ports {i_adv7611_data[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W20 } [get_ports {i_adv7611_data[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB22} [get_ports {i_adv7611_data[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y21 } [get_ports {i_adv7611_data[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB21} [get_ports {i_adv7611_data[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA21} [get_ports {i_adv7611_data[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA20} [get_ports {i_adv7611_data[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V19 } [get_ports {i_adv7611_data[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB20} [get_ports {i_adv7611_data[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V18 } [get_ports {i_adv7611_hs}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA19} [get_ports {i_adv7611_de}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN Y19 } [get_ports {i_adv7611_pclk}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AB18} [get_ports {i_adv7611_vs}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W19 } [get_ports {io_adv7611_sda}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN AA18} [get_ports {io_adv7611_scl}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W17 } [get_ports {o_adv7611_rst_n}]

set_property -dict {PACKAGE_PIN AB3  IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[2]}]
set_property -dict {PACKAGE_PIN W2   IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[1]}]
set_property -dict {PACKAGE_PIN AA1  IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[0]}]
set_property -dict {PACKAGE_PIN W1   IOSTANDARD TMDS_33} [get_ports {o_hdmi_clk_p}]
