# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA_work/FPGA_Boards_Git/Xilinx/XI050A/all_test/all_test.srcs/sources_1/ip/tf_pll/tf_pll.xci
# IP: The module: 'tf_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_work/FPGA_Boards_Git/Xilinx/XI050A/all_test/all_test.gen/sources_1/ip/tf_pll/tf_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tf_pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FPGA_work/FPGA_Boards_Git/Xilinx/XI050A/all_test/all_test.gen/sources_1/ip/tf_pll/tf_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'tf_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FPGA_work/FPGA_Boards_Git/Xilinx/XI050A/all_test/all_test.gen/sources_1/ip/tf_pll/tf_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tf_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/FPGA_work/FPGA_Boards_Git/Xilinx/XI050A/all_test/all_test.srcs/sources_1/ip/tf_pll/tf_pll.xci
# IP: The module: 'tf_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA_work/FPGA_Boards_Git/Xilinx/XI050A/all_test/all_test.gen/sources_1/ip/tf_pll/tf_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tf_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FPGA_work/FPGA_Boards_Git/Xilinx/XI050A/all_test/all_test.gen/sources_1/ip/tf_pll/tf_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'tf_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/FPGA_work/FPGA_Boards_Git/Xilinx/XI050A/all_test/all_test.gen/sources_1/ip/tf_pll/tf_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tf_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
