set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design] 
set_property CONFIG_MODE SPIx1 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
 set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR NO [current_design]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_adv7611_pclk_IBUF]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W19} [get_ports {i_clk_25m}]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P17} [get_ports {o_led[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V20} [get_ports {o_led[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V22} [get_ports {o_led[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U21} [get_ports {o_led[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V18} [get_ports {i_key[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V19} [get_ports {i_key[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U18} [get_ports {i_key[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P16} [get_ports {i_key[3]}]


set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H22} [get_ports {i_adv7611_data[23]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H14} [get_ports {i_adv7611_data[22]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H20} [get_ports {i_adv7611_data[21]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H15} [get_ports {i_adv7611_data[20]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J20} [get_ports {i_adv7611_data[19]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G15} [get_ports {i_adv7611_data[18]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J22} [get_ports {i_adv7611_data[17]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G16} [get_ports {i_adv7611_data[16]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J21} [get_ports {i_adv7611_data[15]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G17} [get_ports {i_adv7611_data[14]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K21} [get_ports {i_adv7611_data[13]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H17} [get_ports {i_adv7611_data[12]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K22} [get_ports {i_adv7611_data[11]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H18} [get_ports {i_adv7611_data[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L20} [get_ports {i_adv7611_data[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H19} [get_ports {i_adv7611_data[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L21} [get_ports {i_adv7611_data[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G20} [get_ports {i_adv7611_data[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M20} [get_ports {i_adv7611_data[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J16} [get_ports {i_adv7611_data[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M21} [get_ports {i_adv7611_data[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J19} [get_ports {i_adv7611_data[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J15} [get_ports {i_adv7611_data[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M22} [get_ports {i_adv7611_data[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N20} [get_ports {i_adv7611_de}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K16} [get_ports {i_adv7611_hs}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N22} [get_ports {i_adv7611_vs}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L16} [get_ports {i_adv7611_pclk}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J17} [get_ports {io_adv7611_scl}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K19} [get_ports {io_adv7611_sda}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J14} [get_ports {o_adv7611_rst_n}]

set_property -dict {PACKAGE_PIN AA8 IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[2]}]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[1]}]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[0]}]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD TMDS_33} [get_ports {o_hdmi_clk_p}]
