create_clock -period 40.000 [get_ports i_clk_25m]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_cam_pclk_IBUF[0]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_cam_pclk_IBUF[1]]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN W19  } [get_ports {i_clk_25m}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN V18  } [get_ports {i_rst_n}]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N4 } [get_ports {o_cam_pwdn[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P4 } [get_ports {i_cam_pclk[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K2 } [get_ports {i_cam_data[0][7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M6 } [get_ports {i_cam_data[0][6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J1 } [get_ports {i_cam_data[0][5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L5 } [get_ports {i_cam_data[0][4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J6 } [get_ports {i_cam_data[0][3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L3 } [get_ports {i_cam_data[0][2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J4 } [get_ports {i_cam_data[0][1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L6 } [get_ports {i_cam_data[0][0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J5 } [get_ports {o_cam_rst_n[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K6 } [get_ports {io_cam_sda[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H4 } [get_ports {i_cam_href[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K4 } [get_ports {io_cam_scl[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H3 } [get_ports {i_cam_vsync[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J2 } [get_ports {o_cam_pwdn[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H2 } [get_ports {i_cam_pclk[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G4 } [get_ports {i_cam_data[1][7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G1 } [get_ports {i_cam_data[1][6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E3 } [get_ports {i_cam_data[1][5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G2 } [get_ports {i_cam_data[1][4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F1 } [get_ports {i_cam_data[1][3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G3 } [get_ports {i_cam_data[1][2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D2 } [get_ports {i_cam_data[1][1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F4 } [get_ports {i_cam_data[1][0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T3 } [get_ports {o_cam_rst_n[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F3 } [get_ports {io_cam_sda[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E1 } [get_ports {i_cam_href[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E2 } [get_ports {io_cam_scl[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN B1 } [get_ports {i_cam_vsync[1]}]

set_property -dict {PACKAGE_PIN AA8 IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[2]}]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[1]}]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD TMDS_33} [get_ports {o_hdmi_d_p[0]}]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD TMDS_33} [get_ports {o_hdmi_clk_p}]

# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_cke}] #恒3V3
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_cs_n}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[0]}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[1]}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[2]}] #恒GND
# set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN   } [get_ports {o_sdram_dqm[3]}] #恒GND
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C19 } [get_ports {o_sdram_clk}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C14 } [get_ports {o_sdram_we_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D16 } [get_ports {o_sdram_cas_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F13 } [get_ports {o_sdram_ras_n}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F16 } [get_ports {o_sdram_ba[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D15 } [get_ports {o_sdram_ba[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F14 } [get_ports {o_sdram_addr[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D14 } [get_ports {o_sdram_addr[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E14 } [get_ports {o_sdram_addr[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E17 } [get_ports {o_sdram_addr[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D19 } [get_ports {o_sdram_addr[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F18 } [get_ports {o_sdram_addr[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D17 } [get_ports {o_sdram_addr[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F19 } [get_ports {o_sdram_addr[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E18 } [get_ports {o_sdram_addr[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E16 } [get_ports {o_sdram_addr[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F15 } [get_ports {o_sdram_addr[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A13 } [get_ports {io_sdram_dq[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A19 } [get_ports {io_sdram_dq[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B13 } [get_ports {io_sdram_dq[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A20 } [get_ports {io_sdram_dq[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C13 } [get_ports {io_sdram_dq[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C18 } [get_ports {io_sdram_dq[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B18 } [get_ports {io_sdram_dq[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A18 } [get_ports {io_sdram_dq[7]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D22 } [get_ports {io_sdram_dq[8]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E19 } [get_ports {io_sdram_dq[9]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E21 } [get_ports {io_sdram_dq[10]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F21 } [get_ports {io_sdram_dq[11]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  E22 } [get_ports {io_sdram_dq[12]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  F20 } [get_ports {io_sdram_dq[13]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G22 } [get_ports {io_sdram_dq[14]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  G21 } [get_ports {io_sdram_dq[15]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A14 } [get_ports {io_sdram_dq[16]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B17 } [get_ports {io_sdram_dq[17]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C17 } [get_ports {io_sdram_dq[18]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A15 } [get_ports {io_sdram_dq[19]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B16 } [get_ports {io_sdram_dq[20]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B15 } [get_ports {io_sdram_dq[21]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A16 } [get_ports {io_sdram_dq[22]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C15 } [get_ports {io_sdram_dq[23]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  A21 } [get_ports {io_sdram_dq[24]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C20 } [get_ports {io_sdram_dq[25]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B21 } [get_ports {io_sdram_dq[26]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  C22 } [get_ports {io_sdram_dq[27]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B22 } [get_ports {io_sdram_dq[28]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D20 } [get_ports {io_sdram_dq[29]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  B20 } [get_ports {io_sdram_dq[30]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN  D21 } [get_ports {io_sdram_dq[31]}]

